apiVersion: v1
kind: Service
metadata:
  name: quizservice-service
  namespace: default
  labels:
    app: quizservice
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: quizservice
  type: NodePort